### PR TITLE
Update PR

### PR DESCRIPTION
**Pull request by tyrellshawn**
Test

### CODE REVIEW

**Comment by tyrellshawn** [comment]
Accident

**Comment by rvdende** [comment]
Yeah the code base has changed quite a bit :)

**Comment by tyrellshawn** [comment]
I'm unable to sign in now even though it's the same url, root user and password. Any idea?

**Comment by rvdende** [comment]
@tyrellshawn be sure to remove any trailing /sql or /rpc paths on the url. This is now done automatically.
You can also press F12 and look in the network tab under Fetch/XHR to see details about the failed request.

**Comment by tyrellshawn** [comment]
Thanks @rvdende  it is working now after I reduced the trailing /rpc path on the url

**Pull request closed without merging**
